config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "todolists#index"

  resources :todolists do
    member do
      post :finished
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  validates_presence_of :name, :due_date, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:edit, :update, :destroy, :finished,:show]
  def index
    @todolists = Todolist.all
  end

  def new
    @todolists = Todolist.new
  end

  def create
    @todolists = Todolist.new(todolist_params)
    if @todolists.save
      redirect_to todolists_url
    else
      render  :action => :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @todolists.update_attributes(todolist_params)
      redirect_to todolists_url
    else
      render  :action => :new
    end
  end

  def finished
     @todolists.update_attributes(finished: !(@todolists.finished))
    redirect_to todolists_url
 end

  #redirect_to todolist_path(@todolists)


  def destroy
    @todolists.destroy
    redirect_to todolists_url
  end
end

private

def set_todolist
   @todolists = Todolist.find(params[:id])
 end

def todolist_params
  params.require(:todolist).permit(:name, :due_date, :description ,:finished,:show)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/_form.html.erb
<% if @todolists.errors.present? %>
  <ul>
    <% @todolists.errors.each do |error, message| %>
      <h3><ol class="alert alert-danger"> <%= "#{error.capitalize} #{message}" %></ol><h3>
    <% end %>
  </ul>
<% end %>
<div class = "container2">
  <%= form_for @todolists do |f| %>
<h4><div class="label label-primary">
    <%= f.label :標题 %>
</div></h4>
 <div class="form-group">
    <%= f.text_field :name %>
  </div>
<h4><ul class="label label-primary">
    <%= f.label :截止日期 %>
</ul></h4>
  <div class="form-group">
    <%= f.text_field :due_date %>
  </div>
<h4><div class="label label-primary">
    <%= f.label :描述 %>
</div></h4>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div>
  <%= f.submit button,class: 'btn btn-defaults' %>
</div>
<% end %>
</div>

app/views/todolists/edit.html.erb
<%= render :partial => "form" , locals: { button: 'UPDATE' } %>

app/views/todolists/index.html.erb
<div class ="container">
  <table class="table">
    <thead>
      <tr class="active">
        <th>勾選</th>
        <th>標題</th>
        <th>到期日</th>
        <th>描述</th>
        <th>    </th>
        <th>
        <th>
          <button>
           <%=link_to"新增＋",new_todolist_path %>
           </button>
        </th>
      </tr>
    </thead>
  <% @todolists.each do |todolist| %>
     <tr>
        <% if todolist.finished %>
          <td>
            <%= link_to finished_todolist_path(todolist), method: :post do %>
              <span class="glyphicon glyphicon-check"></span>
              <td class = "checked">
              <%= todolist.name%>
            </td>

            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to finished_todolist_path(todolist), method: :post do %>
              <span class="glyphicon glyphicon-unchecked"></span>
            <% end %>
            <td >
            <%= todolist.name%>
          </td>
          </td>
        <% end %>

      <td>
      <%= todolist.due_date%>
      </td>
      <td>
      <%= todolist.description%>
      </td>
      <td>
        <button class="btn btn-default">
      <%= link_to "詳細",todolist_path(todolist)%>
      </button>
      </td>
      <td>
        <button class="btn btn-default">
      <%= link_to "編輯",edit_todolist_path(todolist)%>
      </button>
      </td>
      <td>
        <% if (todolist.due_date-Date.today).to_i>-1%>
        <button class="btn btn-default">
          <%= link_to "刪除",todolist_path(todolist),method: :delete,data:{confirm:"Are you sure?"}%>
       </button>
       <%else %>
       <button class="btn btn-danger">
         過期
         </button>
       <% end%>
      </td>
    </tr>
    <% end %>
</table>
</div>

app/views/todolists/new.html.erb
<%= render :partial => "form", locals: { button: 'New' }  %>

app/views/todolists/show.html.erb
<div class="container3">
<tbody>

  <h4><div class="label label-default">
  標題
  </div></h4>

  <div class="well">
      <tr>
  <%= @todolists.name %>
</tr>
  </div>



  <h4><label class="label label-default">
  到期日
  </label></h4>

  <div class="well">
      <tr>
  <%= @todolists.due_date %>
</tr>
  </div>



  <h4><div class="label label-default">
  描述
  </div></h4>

  <div class="well">
      <tr>
  <%= @todolists.description %>
</tr>
  </div>


<button class="btn btn-default">
<%= link_to 'Back to index', todolists_path %>
</button>

</tbody>
</div>